### ISSUE TITLE
[bug] It doesn't send headers now.

### ISSUE THREAD

**Issue by tonitruif** [bewisse/modheader#26] opened 2019-12-12 05:10 UTC

**Comment by n8v8R** [comment] 2019-12-12 08:47
see #22 #23 #25

**Comment by hao1300** [comment] 2019-12-12 16:04
Can you let me know if this is still repro-able in 2.5.4 and whether it is a dupe of #25?

**Comment by tonitruif** [comment] 2019-12-12 16:07
Now headers work properly

**Closed** 2019-12-12 16:10 UTC
