### ISSUE TITLE
Unable to attach header to CORS requests in Chrome 76

### ISSUE THREAD

**Issue by sunb0002** [bewisse/modheader#10] opened 2019-08-14 07:15 UTC
My website is hosted in localhost:3000, and it fires Ajax request to localhost:8080.
With mod-header I'm able to see additional headers with requests to :3000, but not with requests to :8080

I found the release note below:

** What is new in 2.3.9 **
- Simplify the CORS fix now that Chrome actually document how to fix it.

Could you please let me know how to enable those additional headers for my :8080 requests?
Thanks a lot.

**Comment by zayats103** [comment] 2019-08-15 06:38
I have same problems with Chrome, CORS requests do not contain headers I set though the plugin

**Comment by hao1300** [comment] 2019-08-16 13:29
If you open up the Network tab, do you see 'Provisional headers are shown' under Request Headers? If so, then Chrome doesn't actually send the full request across the wire. We don't do anything different for localhost (or different ports of localhost) and all requests should get the modified headers applied (unless filter is set). However, we rely on the browser to honor their API, so there may be some quirks in Chrome and is causing the issue.

ModHeader also exist in Firefox. Can you check install it in Firefox and see if the same issue exists? That will help narrow down whether the issue is from the browser or from the extension code itself.

**Comment by zayats103** [comment] 2019-08-16 14:43
I had to switch to Firefox because of this weird behaviour. In Firefox it is working perfectly so looks like it is caused by some internal changes in Chrome.

**Comment by sunb0002** [comment] 2019-08-20 16:56
Thanks @zayats103 and @hao1300  guess I will just switch to Firefox as well. Chrome 76 CORS change seems to have caused many troubles.

**Comment by zayats103** [comment] 2019-08-22 07:33
@sunb0002 But switching to another browser is not a solution :). 
@hao1300 Looks like the problem is caused by some Chrome specific handling of CORS requests. Is it possible to fix it or Chrome restricted changing headers for CORS requests?

**Comment by hao1300** [comment] 2019-08-22 13:42
Can you file a bug on [Chromium](https://bugs.chromium.org/p/chromium/issues/list) about this and add me to the bug? The problem lies in the browser and needs to be fixed at the browser level.

**Comment by heliumxe** [comment] 2019-09-18 06:16
https://bugs.chromium.org/p/chromium/issues/detail?id=989443

**Comment by hao1300** [comment] 2019-10-20 13:56
Seems like https://bugs.chromium.org/p/chromium/issues/detail?id=989443 has been closed. Closing this bug with the assumption that Chromium will release with their fix.

**Closed by hao1300** 2019-10-20 13:56 UTC
